
-- Generated by the database client.
CREATE TABLE professors(
    id SERIAL NOT NULL,
    full_name varchar(200) NOT NULL,
    department varchar(200),
    active varchar DEFAULT 'S'::bpchar,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE courses(
    id SERIAL NOT NULL,
    course_name varchar(100) NOT NULL,
    course_code varchar(20) NOT NULL,
    credit_hours integer,
    professor_id integer,
    active character(1) DEFAULT 'S'::bpchar,
    PRIMARY KEY(id),
    CONSTRAINT courses_professor_id_fkey FOREIGN key(professor_id) REFERENCES professors(id)
);
CREATE UNIQUE INDEX courses_course_code_key ON public.courses USING btree (course_code);


-- Generated by the database client.
CREATE TABLE students(
    id SERIAL NOT NULL,
    full_name varchar(200) NOT NULL,
    enrollment_number varchar(20) NOT NULL,
    birth_date date,
    course varchar(200) NOT NULL,
    active varchar DEFAULT 'S'::bpchar,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX students_enrollment_number_key ON public.students USING btree (enrollment_number);


-- Generated by the database client.
CREATE TABLE assessments(
    id SERIAL NOT NULL,
    student_id integer NOT NULL,
    course_id integer NOT NULL,
    grade numeric(4,2) NOT NULL,
    semester varchar(10) NOT NULL,
    evaluation_date date,
    active character(1) DEFAULT 'S'::bpchar,
    PRIMARY KEY(id),
    CONSTRAINT assessments_student_id_fkey FOREIGN key(student_id) REFERENCES students(id),
    CONSTRAINT assessments_course_id_fkey FOREIGN key(course_id) REFERENCES courses(id)
);
