### Listar estudantes (GET)
GET http://localhost:8000/professor
Accept: application/json

### Colocar ID no final da URL
GET http://localhost:8000/professor/2
Accept: application/json


### Criar estudante (POST)
POST http://localhost:8000/professor
Content-Type: application/json
Accept: application/json

{
  "full_name": "José de Almeida",
  "department": "Marketing",
  "active":"S"
}

### atualizar estudante (POST)
PUT http://localhost:8000/professor/3
Content-Type: application/json
Accept: application/json

{
  "full_name": "Olivia da Silva Mendonça",
  "department": "Mechanical Engineering",
  "active":"S"
}

####
DELETE  http://localhost:8000/professor/2
Accept: application/json



