### Listar estudantes (GET)
GET http://localhost:8000/student
Accept: application/json

### Colocar ID no final da URL
GET http://localhost:8000/student/1
Accept: application/json


### Criar estudante (POST)
POST http://localhost:8000/student
Content-Type: application/json
Accept: application/json

{
  "full_name": "Rafaela das Graças",
  "enrollment_number": "2025985",
  "birth_date": "2006-07-08",
  "course": "Jornalismo",
  "active":"S"
}

### atualizar estudante (POST)
PUT http://localhost:8000/student/11
Content-Type: application/json
Accept: application/json

{
  "full_name": "Rafaela Carneiro",
  "enrollment_number": "2025985",
  "birth_date": "2006-07-08",
  "course": "Engenharia da Computação",
  "active":"S"
}

###
DELETE  http://localhost:8000/student/6
Accept: application/json



